lang: ja
timezone: Asia/Tokyo
url: "https://job-list.missconnect.jp"
markdown: kramdown
permalink: pretty
baseurl: ""
collections:
  jobs:
    output: true
    permalink: /jobs/:name/
exclude:
  - README.md
  - functions
  - apps-script
