lang: ja
timezone: Asia/Tokyo
markdown: kramdown
permalink: pretty
# GitHub Pages用の設定を追加
baseurl: "/entp-sub"
collections:
  jobs:
    output: true
    permalink: /jobs/:name/
exclude:
  - README.md
  - functions
  - apps-script
